- generic [active] [ref=e1]:
  - main [ref=e2]:
    - generic [ref=e4]:
      - complementary [ref=e5]:
        - generic [ref=e6]:
          - img "SmartDoc AI logo" [ref=e8]
          - link "New Property" [ref=e9] [cursor=pointer]:
            - /url: /properties/new
            - img [ref=e10]
            - text: New Property
          - navigation [ref=e11]:
            - link "Dashboard" [ref=e12] [cursor=pointer]:
              - /url: /
              - img [ref=e13]
              - text: Dashboard
            - link "Map View" [ref=e18] [cursor=pointer]:
              - /url: /map
              - img [ref=e19]
              - text: Map View
        - link "Settings" [ref=e22] [cursor=pointer]:
          - /url: /settings
          - img [ref=e23]
          - text: Settings
      - generic [ref=e26]:
        - generic [ref=e27]:
          - generic [ref=e28]:
            - paragraph [ref=e29]: Analytics overzicht
            - navigation [ref=e30]:
              - link "Overview" [ref=e31] [cursor=pointer]:
                - /url: /
              - link "Analytics" [ref=e32] [cursor=pointer]:
                - /url: /analytics
          - generic [ref=e33]:
            - button "Export data (coming soon)" [ref=e35] [cursor=pointer]:
              - img [ref=e36]
              - text: Export Data
            - button "Open notifications" [ref=e41] [cursor=pointer]:
              - img [ref=e42]
              - generic [ref=e45]: "3"
        - generic [ref=e46]:
          - generic [ref=e47]:
            - article [ref=e48]:
              - paragraph [ref=e49]: Total properties
              - paragraph [ref=e50]: "5"
            - article [ref=e51]:
              - paragraph [ref=e52]: Properties with issues
              - paragraph [ref=e53]: "5"
            - article [ref=e54]:
              - paragraph [ref=e55]: Total documents
              - paragraph [ref=e56]: "15"
            - article [ref=e57]:
              - paragraph [ref=e58]: Missing documents
              - paragraph [ref=e59]: "0"
            - article [ref=e60]:
              - paragraph [ref=e61]: Upcoming expiries
              - paragraph [ref=e62]: "0"
            - article [ref=e63]:
              - paragraph [ref=e64]: Total red flags
              - paragraph [ref=e65]: "4"
          - generic [ref=e66]:
            - article [ref=e67]:
              - heading "Documents by type" [level=2] [ref=e68]:
                - img [ref=e69]
                - text: Documents by type
              - generic [ref=e71]:
                - generic [ref=e73]:
                  - generic [ref=e74]: EPC
                  - generic [ref=e75]: "5"
                - generic [ref=e79]:
                  - generic [ref=e80]: ASBESTOS
                  - generic [ref=e81]: "5"
                - generic [ref=e85]:
                  - generic [ref=e86]: ELECTRICAL
                  - generic [ref=e87]: "5"
            - article [ref=e90]:
              - heading "Property status distribution" [level=2] [ref=e91]:
                - img [ref=e92]
                - text: Property status distribution
              - generic [ref=e95]:
                - generic [ref=e96]:
                  - paragraph [ref=e98]: Green
                  - paragraph [ref=e99]: "0"
                - generic [ref=e100]:
                  - paragraph [ref=e102]: Orange
                  - paragraph [ref=e103]: "2"
                - generic [ref=e104]:
                  - paragraph [ref=e106]: Red
                  - paragraph [ref=e107]: "3"
          - generic [ref=e108]:
            - article [ref=e109]:
              - heading "Upcoming expiries by month" [level=2] [ref=e110]:
                - img [ref=e111]
                - text: Upcoming expiries by month
              - generic [ref=e115]:
                - generic [ref=e116]:
                  - generic [ref=e117]: 2032-08
                  - generic [ref=e118]: "3"
                - generic [ref=e119]:
                  - generic [ref=e120]: 2036-01
                  - generic [ref=e121]: "13"
                - generic [ref=e122]:
                  - generic [ref=e123]: 2051-03
                  - generic [ref=e124]: "3"
                - generic [ref=e125]:
                  - generic [ref=e126]: 2056-03
                  - generic [ref=e127]: "1"
            - article [ref=e128]:
              - heading "Missing documents by type" [level=2] [ref=e129]:
                - img [ref=e130]
                - text: Missing documents by type
              - generic [ref=e133]:
                - generic [ref=e135]:
                  - generic [ref=e136]: ASBESTOS
                  - generic [ref=e137]: "0"
                - generic [ref=e140]:
                  - generic [ref=e141]: ELECTRICAL
                  - generic [ref=e142]: "0"
                - generic [ref=e145]:
                  - generic [ref=e146]: EPC
                  - generic [ref=e147]: "0"
          - generic [ref=e149]:
            - article [ref=e150]:
              - heading "Recently uploaded documents" [level=2] [ref=e151]
              - list [ref=e152]:
                - listitem [ref=e153]:
                  - generic [ref=e154]: EPC · Bondgenotenlaan 88, 3000 Leuven
                  - generic [ref=e155]: 4/25/2026
                - listitem [ref=e156]:
                  - generic [ref=e157]: ASBESTOS · Parkstraat 88, 3000 Leuven
                  - generic [ref=e158]: 4/24/2026
                - listitem [ref=e159]:
                  - generic [ref=e160]: ELECTRICAL · Parkstraat 88, 3000 Leuven
                  - generic [ref=e161]: 4/24/2026
                - listitem [ref=e162]:
                  - generic [ref=e163]: EPC · Parkstraat 88, 3000 Leuven
                  - generic [ref=e164]: 4/24/2026
                - listitem [ref=e165]:
                  - generic [ref=e166]: ELECTRICAL · Bondgenotenlaan 42, Leuven
                  - generic [ref=e167]: 4/24/2026
                - listitem [ref=e168]:
                  - generic [ref=e169]: ASBESTOS · Bondgenotenlaan 88, 3000 Leuven
                  - generic [ref=e170]: 4/22/2026
            - article [ref=e171]:
              - heading "Recently created properties" [level=2] [ref=e172]:
                - img [ref=e173]
                - text: Recently created properties
              - list [ref=e175]:
                - listitem [ref=e176]:
                  - generic [ref=e177]: Parkstraat 88, 3000 Leuven
                  - generic [ref=e178]: 4/24/2026
                - listitem [ref=e179]:
                  - generic [ref=e180]: Bondgenotenlaan 88, 3000 Leuven
                  - generic [ref=e181]: 4/18/2026
                - listitem [ref=e182]:
                  - generic [ref=e183]: Dekenstraat 145 3000 leuven
                  - generic [ref=e184]: 3/24/2026
                - listitem [ref=e185]:
                  - generic [ref=e186]: Muntstraat 2, Leuven
                  - generic [ref=e187]: 3/24/2026
                - listitem [ref=e188]:
                  - generic [ref=e189]: Bondgenotenlaan 42, Leuven
                  - generic [ref=e190]: 3/24/2026
  - alert [ref=e191]