- generic [active] [ref=e1]:
  - main [ref=e2]:
    - generic [ref=e4]:
      - complementary [ref=e5]:
        - generic [ref=e6]:
          - img "SmartDoc AI logo" [ref=e8]
          - link "New Property" [ref=e9] [cursor=pointer]:
            - /url: /properties/new
            - img [ref=e10]
            - text: New Property
          - navigation [ref=e11]:
            - link "Dashboard" [ref=e12] [cursor=pointer]:
              - /url: /
              - img [ref=e13]
              - text: Dashboard
            - link "Map View" [ref=e18] [cursor=pointer]:
              - /url: /map
              - img [ref=e19]
              - text: Map View
        - navigation [ref=e22]:
          - link "Settings" [ref=e23] [cursor=pointer]:
            - /url: /settings
            - img [ref=e24]
            - text: Settings
      - main [ref=e27]:
        - generic [ref=e28]:
          - generic [ref=e29]:
            - generic [ref=e30]:
              - img [ref=e31]
              - textbox "Search properties on map..." [ref=e34]
            - generic [ref=e35]: Map workspace
          - generic [ref=e36]:
            - button "Export data (coming soon)" [ref=e38] [cursor=pointer]:
              - img [ref=e39]
              - text: Export Data
            - button "Open notifications" [ref=e45] [cursor=pointer]:
              - img [ref=e46]
              - generic [ref=e49]: "3"
        - generic [ref=e51]:
          - generic [ref=e52]:
            - navigation [ref=e53]:
              - generic [ref=e54]: Properties
              - generic [ref=e55]: ›
              - generic [ref=e56]: Map View
            - heading "Properties on the Map" [level=1] [ref=e57]
            - paragraph [ref=e58]: Showing 5 assets with geocoded coordinates.
          - button "Refresh" [ref=e60] [cursor=pointer]:
            - img [ref=e61]
            - text: Refresh
        - region "Kaart met panden" [ref=e66]:
          - complementary [ref=e67]:
            - generic [ref=e68]:
              - generic [ref=e69]:
                - heading "Property List" [level=3] [ref=e70]
                - generic [ref=e71]: 5 assets
              - paragraph [ref=e72]: Select a property to open its detail page. Status tags correspond with markers on the map.
            - generic [ref=e73]:
              - link "C121C3B5 Attention Bondgenotenlaan 42, Leuven 42, Bondgenotenlaan, Sint-Maartensdal, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien" [ref=e74] [cursor=pointer]:
                - /url: /properties/c121c3b5-d552-4951-9054-115b3487f61d
                - generic [ref=e75]:
                  - generic [ref=e76]: C121C3B5
                  - generic [ref=e77]: Attention
                - heading "Bondgenotenlaan 42, Leuven" [level=4] [ref=e78]
                - paragraph [ref=e79]: 42, Bondgenotenlaan, Sint-Maartensdal, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien
              - link "FC3D9986 Critical Muntstraat 2, Leuven 2, Muntstraat, Sint-Maartensdal, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien" [ref=e80] [cursor=pointer]:
                - /url: /properties/fc3d9986-f67e-469b-9d85-8d9373c1f5a2
                - generic [ref=e81]:
                  - generic [ref=e82]: FC3D9986
                  - generic [ref=e83]: Critical
                - heading "Muntstraat 2, Leuven" [level=4] [ref=e84]
                - paragraph [ref=e85]: 2, Muntstraat, Sint-Maartensdal, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien
              - link "2734801D Attention Parkstraat 88, 3000 Leuven 88, Parkstraat, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien" [ref=e86] [cursor=pointer]:
                - /url: /properties/2734801d-59c8-4dc6-8180-b6044afb99db
                - generic [ref=e87]:
                  - generic [ref=e88]: 2734801D
                  - generic [ref=e89]: Attention
                - heading "Parkstraat 88, 3000 Leuven" [level=4] [ref=e90]
                - paragraph [ref=e91]: 88, Parkstraat, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien
              - link "66E8EBF5 Critical Dekenstraat 145 3000 leuven Dekenstraat, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien" [ref=e92] [cursor=pointer]:
                - /url: /properties/66e8ebf5-af40-4b89-a688-b9528f263b59
                - generic [ref=e93]:
                  - generic [ref=e94]: 66E8EBF5
                  - generic [ref=e95]: Critical
                - heading "Dekenstraat 145 3000 leuven" [level=4] [ref=e96]
                - paragraph [ref=e97]: Dekenstraat, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien
              - link "BE232ADC Critical Bondgenotenlaan 88, 3000 Leuven 88, Bondgenotenlaan, Sint-Maartensdal, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien" [ref=e98] [cursor=pointer]:
                - /url: /properties/be232adc-bb16-44d5-9b98-be23308ed240
                - generic [ref=e99]:
                  - generic [ref=e100]: BE232ADC
                  - generic [ref=e101]: Critical
                - heading "Bondgenotenlaan 88, 3000 Leuven" [level=4] [ref=e102]
                - paragraph [ref=e103]: 88, Bondgenotenlaan, Sint-Maartensdal, Leuven, Vlaams-Brabant, Vlaanderen, 3000, België / Belgique / Belgien
          - generic [ref=e105]:
            - generic:
              - generic:
                - button [ref=e106] [cursor=pointer]
                - button [ref=e108] [cursor=pointer]
                - button [ref=e110] [cursor=pointer]
                - button [ref=e112] [cursor=pointer]
                - button [ref=e114] [cursor=pointer]
            - generic:
              - generic [ref=e116]:
                - button "Zoom in" [ref=e117] [cursor=pointer]: +
                - button "Zoom out" [ref=e118] [cursor=pointer]: −
              - generic [ref=e119]:
                - link "Leaflet" [ref=e120] [cursor=pointer]:
                  - /url: https://leafletjs.com
                  - img [ref=e121]
                  - text: Leaflet
                - text: "| ©"
                - link "OpenStreetMap" [ref=e125] [cursor=pointer]:
                  - /url: https://www.openstreetmap.org/copyright
  - alert [ref=e126]